projects:
  prisma:
    schema: ./src/schema.graphql
  database:
    schema: ./prisma/prisma.yml
    extensions:
      codegen:
        generates:
          ./prisma.graphql:
            plugins:
              - schema-ast